# 1. Pobrac obraz linux (jak najmniejszy)
# 2. Pobrac niezbedne narzedzia (java, gradle, +++)
# 3. Pobrac repozytorum EmailSpringApp z GitHub
# 4. Zbudowac plik .jar ze zrodel z 3.
# 5. Odpalic aplikacje na wybranym porcie
# 6. Zweryfikowac dzialanie uzywajac Postman